'use server'

import { createClient }   from '@/lib/supabase/server'
import { getAdminClient } from '@/lib/supabase/admin'
import { revalidatePath }  from 'next/cache'
import { auditLog }        from '@/lib/supabase/audit'

// ── Auth guard ────────────────────────────────────────────────────────────────

async function getProfile() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Non authentifié.' as const, supabase, user: null, profile: null }

  const { data: profile } = await supabase
    .from('users')
    .select('id, role, company_id, full_name, is_active, is_platform_admin')
    .eq('id', user.id)
    .single()

  if (!profile || !profile.is_active || profile.is_platform_admin)
    return { error: 'Accès refusé.' as const, supabase, user, profile: null }
  if (!['owner', 'admin', 'vendor'].includes(profile.role))
    return { error: 'Accès refusé.' as const, supabase, user, profile: null }

  return { error: null, supabase, user, profile }
}

// ── Create return ─────────────────────────────────────────────────────────────

export interface ReturnItemPayload {
  saleItemId:  string
  productId:   string
  qtyReturned: number
  unitPrice:   number
  tileAreaM2:  number | null
  totalPrice:  number
}

export async function createReturn(payload: {
  saleId:     string
  resolution: 'refund' | 'credit_note'
  notes:      string
  items:      ReturnItemPayload[]
}) {
  const { error, supabase, user, profile } = await getProfile()
  if (error || !user || !profile) return { error: error ?? 'Accès refusé.' }

  if (!payload.saleId) return { error: 'Vente requise.' }
  if (!payload.items.length) return { error: 'Aucun article à retourner.' }

  // Validate the sale belongs to this company and is delivered
  const { data: sale } = await supabase
    .from('sales')
    .select('id, sale_number, customer_name, status, company_id')
    .eq('id', payload.saleId)
    .single()

  if (!sale || sale.company_id !== profile.company_id)
    return { error: 'Vente introuvable.' }
  if (sale.status !== 'delivered')
    return { error: 'Seules les ventes livrées peuvent faire l\'objet d\'un retour.' }

  // Validate qty > 0 and items have valid qty
  for (const item of payload.items) {
    if (item.qtyReturned <= 0) return { error: 'La quantité retournée doit être positive.' }
    if (item.totalPrice < 0)   return { error: 'Montant invalide.' }
  }

  const totalAmount = Math.round(payload.items.reduce((s, i) => s + i.totalPrice, 0))

  // Insert the return header (return_number generated by trigger)
  const { data: ret, error: retErr } = await supabase
    .from('sale_returns')
    .insert({
      company_id:   profile.company_id,
      sale_id:      payload.saleId,
      status:       'pending',
      resolution:   payload.resolution,
      total_amount: totalAmount,
      notes:        payload.notes.trim() || null,
      created_by:   user.id,
    })
    .select('id, return_number')
    .single()

  if (retErr || !ret) return { error: retErr?.message ?? 'Erreur lors de la création.' }

  // Insert return items
  const { error: itemsErr } = await supabase
    .from('sale_return_items')
    .insert(payload.items.map(i => ({
      return_id:    ret.id,
      sale_item_id: i.saleItemId,
      product_id:   i.productId,
      qty_returned: i.qtyReturned,
      unit_price:   Math.round(i.unitPrice),
      tile_area_m2: i.tileAreaM2,
      total_price:  Math.round(i.totalPrice),
    })))

  if (itemsErr) {
    // Clean up orphan header
    await supabase.from('sale_returns').delete().eq('id', ret.id)
    return { error: itemsErr.message }
  }

  await auditLog({
    user_id:            user.id,
    user_role_snapshot: profile.role,
    action_type:        'RETURN_CREATED',
    entity_type:        'sale_returns',
    entity_id:          ret.id,
    company_id:         profile.company_id,
    data_after: {
      return_number: ret.return_number,
      sale_id:       payload.saleId,
      sale_number:   sale.sale_number,
      resolution:    payload.resolution,
      total_amount:  totalAmount,
    },
  })

  revalidatePath('/returns')
  revalidatePath('/warehouse')
  return { success: true, returnNumber: ret.return_number }
}

// ── Validate return (owner / admin only) ──────────────────────────────────────

export async function validateReturn(returnId: string) {
  const { error, user, profile } = await getProfile()
  if (error || !user || !profile) return { error: error ?? 'Accès refusé.' }
  if (!['owner', 'admin'].includes(profile.role)) return { error: 'Accès refusé.' }

  const supabase = await createClient()
  const { data: ret } = await supabase
    .from('sale_returns')
    .select('id, return_number, status, sale_id, company_id')
    .eq('id', returnId)
    .single()

  if (!ret || ret.company_id !== profile.company_id) return { error: 'Retour introuvable.' }
  if (ret.status !== 'pending') return { error: 'Ce retour n\'est plus en attente.' }

  // Call SECURITY DEFINER RPC — updates stock + sets validated
  const { error: rpcErr } = await getAdminClient().rpc('validate_sale_return', {
    p_return_id:    returnId,
    p_validated_by: user.id,
  })

  if (rpcErr) return { error: rpcErr.message }

  await auditLog({
    user_id:            user.id,
    user_role_snapshot: profile.role,
    action_type:        'RETURN_VALIDATED',
    entity_type:        'sale_returns',
    entity_id:          returnId,
    company_id:         profile.company_id,
    data_after: { return_number: ret.return_number, sale_id: ret.sale_id },
  })

  revalidatePath('/returns')
  revalidatePath('/warehouse')
  revalidatePath('/dashboard')
  return { success: true }
}

// ── Cancel return (owner / admin only) ────────────────────────────────────────

export async function cancelReturn(returnId: string) {
  const { error, user, profile } = await getProfile()
  if (error || !user || !profile) return { error: error ?? 'Accès refusé.' }
  if (!['owner', 'admin'].includes(profile.role)) return { error: 'Accès refusé.' }

  const supabase = await createClient()
  const { data: ret } = await supabase
    .from('sale_returns')
    .select('id, return_number, status, company_id')
    .eq('id', returnId)
    .single()

  if (!ret || ret.company_id !== profile.company_id) return { error: 'Retour introuvable.' }
  if (ret.status !== 'pending') return { error: 'Seuls les retours en attente peuvent être annulés.' }

  const { error: updErr } = await supabase
    .from('sale_returns')
    .update({ status: 'cancelled' })
    .eq('id', returnId)

  if (updErr) return { error: updErr.message }

  await auditLog({
    user_id:            user.id,
    user_role_snapshot: profile.role,
    action_type:        'RETURN_CANCELLED',
    entity_type:        'sale_returns',
    entity_id:          returnId,
    company_id:         profile.company_id,
    data_after: { return_number: ret.return_number },
  })

  revalidatePath('/returns')
  return { success: true }
}
